# Generated by Django 3.0.7 on 2021-01-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('desc', models.TextField()),
                ('cat', models.CharField(max_length=32)),
                ('price', models.PositiveIntegerField()),
                ('type', models.BooleanField(choices=[('income', True), ('expense', False)])),
            ],
        ),
    ]
