# Generated by Django 3.0.7 on 2021-01-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='type',
            field=models.BooleanField(choices=[(True, 'income'), (False, 'expense')]),
        ),
    ]
