# Generated by Django 3.0.7 on 2020-12-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0002_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
