# Generated by Django 3.0.7 on 2020-12-19 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_cases_appointed_date'),
        ('pharma', '0003_prescription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='case',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Cases'),
        ),
    ]
