# Generated by Django 3.0.7 on 2020-12-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0004_auto_20201219_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('c', 'Created'), ('p', 'Prescribed'), ('d', 'Delivered')], default='c', max_length=2),
        ),
    ]
