# Generated by Django 3.0.7 on 2020-12-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0006_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
