# Generated by Django 3.0.7 on 2020-12-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
        ('pharma', '0007_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharma.Stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Staff')),
            ],
        ),
    ]
