# Generated by Django 3.0.7 on 2020-12-23 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0009_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='case',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.AddField(
            model_name='medicine',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharma.Prescription'),
        ),
    ]
