# Generated by Django 3.0.7 on 2020-12-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0013_auto_20201223_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
