# Generated by Django 3.0.7 on 2020-12-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0015_editedprescription_epmedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='bill',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharma.Bill'),
        ),
    ]
