# Generated by Django 3.0.7 on 2020-12-25 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0016_prescription_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epmedicine',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharma.EditedPrescription'),
        ),
    ]
