# Generated by Django 3.0.7 on 2020-12-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('t', 'trans')], max_length=20)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B+'), ('O-', 'O+'), ('AB-', 'AB-')], max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default=None, max_length=10)),
            ],
        ),
    ]
