# Generated by Django 3.0.7 on 2020-12-18 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('state', models.CharField(choices=[('e', 'Emergency'), ('n', 'Normal'), ('c', 'Checkup')], max_length=3)),
                ('status', models.CharField(choices=[('t', 'ToDo'), ('i', 'in progress'), ('d', 'done')], max_length=3)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Patient')),
            ],
        ),
    ]
