# Generated by Django 3.0.7 on 2020-12-19 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='appointed_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='appointment date'),
            preserve_default=False,
        ),
    ]
