# Generated by Django 3.0.7 on 2020-12-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20201221_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
